Logging Architecture
OCP-on-NERC/docs pull request #53
Opened 2023-12-14 10:40 UTC by bnshr

Describe the NERC logging architecture by providing logical and schematic digram.

2023-12-18 09:36 UTC, schwesig requested changes
just a few minor changes (the team name and some typos)

2023-12-18 09:36 UTC, schwesig commented on architecture/logging/portfolio.md
> +For better understanding of the development, test, deploy and
```suggestion
For better understanding of the development, test, deploy, and operation, the following diagram identified several parts of the system that composed the structure of the logging system in NERC.
```

2023-12-18 09:36 UTC, schwesig commented on architecture/logging/portfolio.md
> +operation, the following diagram identified several parts of the
```suggestion
```

2023-12-18 09:36 UTC, schwesig commented on architecture/logging/portfolio.md
> +system that composed the structure of the logging system in NERC.
```suggestion
```

2023-12-18 09:36 UTC, schwesig commented on architecture/logging/portfolio.md
> +For better understanding of the development, test, deploy and
- avoiding to split one sentence over multiple line

2023-12-18 09:36 UTC, schwesig commented on architecture/logging/portfolio.md
> +1. The read request comes from the admin users who have the permission
```suggestion
1. The read request comes from the admin users who have the permission (by adding into [nerc-logs-metrics](https://github.com/orgs/OCP-on-NERC/teams/nerc-logs-metrics) group in GitHub) to read the logs from the OpenShift Production (as an example) Cluster Console.
```

2023-12-18 09:36 UTC, schwesig commented on architecture/logging/portfolio.md
> +(by adding into nerc-logs group in GitHub) to read the logs from
```suggestion
```

2023-12-18 09:36 UTC, schwesig commented on architecture/logging/portfolio.md
> +the OpenShift Production (as an example) Cluster Console.
```suggestion
```

2023-12-18 09:36 UTC, schwesig commented on architecture/logging/portfolio.md
> +This is enabled for them by enabling logging Console Plugin after installing
```suggestion
This is enabled for them by enabling logging Console Plugin after installing OpenShift Logging Operator.
```

2023-12-18 09:36 UTC, schwesig commented on architecture/logging/portfolio.md
> +OpenShift Logging Operator.
```suggestion
```

2023-12-18 09:36 UTC, schwesig commented on architecture/logging/portfolio.md
> +4. The backing store handles the read and write request from the customer, as it provides MCG
```suggestion
4. The backing store handles the read and write request from the customer, as it provides MCG the ability to save the data of the provisioned bucket on top of it. In this architecture, the backing store is AWS:S3 bucket.
```

2023-12-18 09:36 UTC, schwesig commented on architecture/logging/portfolio.md
> +the ability to save the data of the provisioned bucket on top of it. In this architecture, the backing store is AWS:S3 bucket.
```suggestion
```

2023-12-18 09:36 UTC, schwesig commented on architecture/logging/portfolio.md
> +## Schematic Digram
```suggestion
## Schematic Diagram
```

2023-12-18 09:36 UTC, schwesig commented on architecture/logging/portfolio.md
> +The below digram depicts the read and write flow. However, please bear in mind that only essential components are identified for the sake of brevity as lots are happening behind the scene.
```suggestion
The below diagram depicts the read and write flow. However, please bear in mind that only essential components are identified for the sake of brevity as lots are happening behind the scene.
```

2023-12-18 09:36 UTC, schwesig commented on architecture/logging/portfolio.md
> +3. To fetch the log data from the long-term storage, the request is forwarded to the NooBaa operator, one of the operators in the OpenShift Data Foundation installed in Observability cluster. This op
```suggestion
3. To fetch the log data from the long-term storage, the request is forwarded to the NooBaa operator, one of the operators in the OpenShift Data Foundation installed in Observability cluster. This operator is responsible to manage Multicloud Object Gateway components, such as object bucket claim, bucket classes, and backing store in the OpenShift Data Foundation.
```

2023-12-18 09:36 UTC, schwesig commented on architecture/logging/portfolio.md
> +6. A S3 bucket is provisioned by a Object Bucket Claim for storing data. And the route for the S3 access is provided by the interal CRD called NooBaa.
```suggestion
6. A S3 bucket is provisioned by a Object Bucket Claim for storing data. And the route for the S3 access is provided by the internal CRD called NooBaa.
```

2023-12-18 09:36 UTC, schwesig commented on architecture/logging/portfolio.md
> +> The LOKI ruler continuously evaulates a set of configurable queries and performs an action based on the result. This component is not directly involved during the read request from the cluster admi
```suggestion
> The LOKI ruler continuously evaluates a set of configurable queries and performs an action based on the result. This component is not directly involved during the read request from the cluster admin users, however to generate alerts, it reads the logs from the log store following the same path in the OpenShift Data Foundation. 
```

2023-12-18 09:36 UTC, schwesig commented on architecture/logging/portfolio.md
> +To aggegrate the logs (application, infrastructure and audit) the cluster logging operator is installed in the ACM production clusters. This operator components collects and forwards logs to the log
```suggestion
To aggegrate the logs (application, infrastructure, and audit) the cluster logging operator is installed in the ACM production clusters. This operator components collects and forwards logs to the log store to be saved for reading purpose later.
```

2023-12-18 09:40 UTC, schwesig commented on architecture/logging/portfolio.md
> +1. The read request comes from the admin users who have the permission
- avoid multiple lines
- changing team nerc-logs to nerc-logs-metrics and adding link

2023-12-20 16:28 UTC, computate approved these changes
Looks like the checks are passing now, nice work!
I love all the relevant links in the document, it's very good.
The diagrams are beautiful and clear.

2023-12-20 16:31 UTC, schwesig approved these changes
awesome job @bnshr
approved!

2023-12-20 16:33 UTC, merged

2023-12-21 13:29 UTC, bnshr commented
Thanks for the review and suggestions. 👍