docs: add link to RH docu VictoriaMetrics
OCP-on-NERC/docs pull request #59
Opened 2024-02-21 06:56 UTC by schwesig

[3.2. Exporting metrics to external endpoints](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.9/html/observability/using-observability#exporting-metrics-to-external-endpoints)

2024-02-21 13:35 UTC, larsks commented on architecture/observability/README.md
> +**VictoriaMetrics:** VictoriaMetrics offers an option it is configured to go to a Backup Object Bucket, and on the infra side, the metrics go to a separate metrics bucket with retention. [1]
Instead of using a footnote-style reference, just make the name a link:

```suggestion
**[VictoriaMetrics]:** VictoriaMetrics offers an option it is configured to go to a Backup Object Bucket, and on the infra side, the metrics go to a separate metrics bucket with retention.
```

2024-02-21 13:35 UTC, larsks commented on architecture/observability/README.md
> +[1]: https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.9/html/observability/using-observability#exporting-metrics-to-external-endpoints
```suggestion
[victoriametrics]: https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.9/html/observability/using-observability#exporting-metrics-to-external-endpoints
```

2024-02-21 13:45 UTC, schwesig commented
@larsks thanks; I first didn't think a small chapter would be fair to "block" the headline. But we don't have any other links yet, so this makes sense. I am using your idea.

2024-02-21 13:51 UTC, larsks commented
I think the link to https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.9/html/observability/using-observability#exporting-metrics-to-external-endpoints doesn't really explain what VictoriaMetrics **is**. Maybe the link should go to https://victoriametrics.com/products/open-source/ instead?

Also, I am having a hard time parsing the description:

> VictoriaMetrics offers an option it is configured to go to a Backup Object Bucket, and on the infra side, the metrics go to a separate metrics bucket with retention.

There are some grammar and clarity problems that need correcting there. I'm unable to offer a suggestion because I'm not entirely clear what this sentence is trying to say.

2024-02-21 14:41 UTC, schwesig commented
> I think the link to https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.9/html/observability/using-observability#exporting-metrics-to-external-endpoints doesn't really explain what VictoriaMetrics **is**. Maybe the link should go to https://victoriametrics.com/products/open-source/ instead?
> 
yes, I was thinking this, ... without opening a whole bucket and adding links to all mentioned services, apps, and operators.

2024-02-21 14:42 UTC, schwesig commented
Let me go through the text with Jeet and Harshil later and clarify a few things to make it easier to understand.

2024-02-21 15:03 UTC, larsks commented
I've pushed up some suggested formatting changes. This doesn't address the language.

2024-02-21 17:07 UTC, computate requested changes

2024-02-21 17:07 UTC, computate commented on architecture/observability/README.md
> +- **[VictoriaMetrics]**: VictoriaMetrics offers an option it is configured to go to a Backup Object Bucket, and on the infra side, the metrics go to a separate metrics bucket with retention.
Instead of "VictoriaMetrics offers an option it is configured to go to a Backup Object Bucket", 
Maybe "VictoriaMetrics offers an option to also send metrics to a Backup Object Bucket"

2024-02-21 19:00 UTC, schwesig commented on architecture/observability/README.md
> +- **[VictoriaMetrics]**: VictoriaMetrics offers an option it is configured to go to a Backup Object Bucket, and on the infra side, the metrics go to a separate metrics bucket with retention.
accepted and changed

2024-02-21 19:10 UTC, larsks commented on architecture/observability/README.md
> +- **[VictoriaMetrics]**: VictoriaMetrics offers an option to also send metrics to a Backup Object Bucket, and on the infra side, the metrics go to a separate metrics bucket with retention.
This is still missing the answer to the question, "What is VictoriaMetrics?".  How about:

```suggestion
- **[VictoriaMetrics]**: VictoriaMetrics is an alternative storage backend for Prometheus. It offers an option to store metrics in an object storage service. On the infra side, the metrics go to a separate metrics bucket with a retention policy to limit the space consumed by metrics storage.
```

2024-02-21 19:31 UTC, larsks commented on architecture/observability/README.md
> +- **[Red Hat OpenShift Data Foundation][odf] (ODF)**: ODF is an object storage that is required and made available for Thanos on the RHACM Hub cluster to store all the platform metrics collected from
Maybe:

```suggestion
- **[Red Hat OpenShift Data Foundation][odf] (ODF)**: ODF is a storage operator built on top of Ceph (for block storage) and Noobaa (for object storage). We use it to provide object storage for Thanos on the RHACM Hub cluster to store all the platform metrics collected from each of the managed clusters.
```

2024-02-21 20:09 UTC, schwesig commented
@larsks thanks for all the links. I added some more benefits using VictoriaMetrics in the doc. I hope this answers the why a little bit better.

2024-02-21 20:14 UTC, larsks approved these changes

2024-02-22 01:12 UTC, computate approved these changes

2024-02-22 07:14 UTC, merged